services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gsbrapports
      MYSQL_USER: gsb
      MYSQL_PASSWORD: gsb
    command: --log-bin-trust-function-creators=1
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
